In [25]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df = pd.read_csv("customer_churn_data.csv", index_col="customerID")
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
customerID,,,,,,,,,,,,,,,,,,,,
CUST0000,Male,0,No,Yes,23,No,No phone service,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer,49.85,1146.55,No
CUST0001,Female,0,Yes,No,43,No,No phone service,DSL,Yes,No,Yes,No,Yes,No,Month-to-month,No,Mailed check,100.70,4330.10,Yes
CUST0002,Male,1,No,No,51,Yes,No,DSL,No,Yes,Yes,Yes,No,No,One year,No,Electronic check,97.33,4963.83,Yes
CUST0003,Male,1,No,No,72,Yes,Yes,DSL,Yes,No,Yes,No,No,No,Month-to-month,No,Credit card,101.38,7299.36,No
CUST0004,Male,1,No,No,25,Yes,Yes,DSL,No,No,No,Yes,No,Yes,Month-to-month,No,Electronic check,52.22,1305.50,Yes

In [3]:
df.info()

<class 'pandas.DataFrame'>
Index: 5880 entries, CUST0000 to CUST5879
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            5880 non-null   str
 1   SeniorCitizen     5880 non-null   int64
 2   Partner           5880 non-null   str
 3   Dependents        5880 non-null   str
 4   tenure            5880 non-null   int64
 5   PhoneService      5880 non-null   str
 6   MultipleLines     5880 non-null   str
 7   InternetService   5880 non-null   str
 8   OnlineSecurity    5880 non-null   str
 9   OnlineBackup      5880 non-null   str
 10  DeviceProtection  5880 non-null   str
 11  TechSupport       5880 non-null   str
 12  StreamingTV       5880 non-null   str
 13  StreamingMovies   5880 non-null   str
 14  Contract          5880 non-null   str
 15  PaperlessBilling  5880 non-null   str
 16  PaymentMethod     5880 non-null   str
 17  MonthlyCharges    5880 non-null   float64
 18  TotalCharges      5880 non-null   float64
 19  Churn             5880 non-null   str
dtypes: float64(2), int64(2), str(16)
memory usage: 964.7+ KB

In [15]:
for col in df.columns:
    print(f"{df[col].name}: {df[col].nunique()}")

gender: 2
SeniorCitizen: 2
Partner: 2
Dependents: 2
tenure: 72
PhoneService: 2
MultipleLines: 3
InternetService: 3
OnlineSecurity: 3
OnlineBackup: 3
DeviceProtection: 3
TechSupport: 3
StreamingTV: 3
StreamingMovies: 3
Contract: 3
PaperlessBilling: 2
PaymentMethod: 4
MonthlyCharges: 4439
TotalCharges: 5794
Churn: 2

In [20]:
multinominal_cols = [col for col in df.select_dtypes(include=["object","str"]).columns if df[col].nunique() > 2 ] 
binary_cols = [col for col in df.select_dtypes(include=["object","str"]).columns if df[col].nunique() == 2 ]

In [ ]:
def numericize_col(df, object_cols):
    for col in object_cols:
        df[f'{col}_encoded'] = pd.factorize(df[col])[0]
    return df

df = numericize_col(df, binary_cols)

In [79]:
# Random Forest Classifier Pipeline
preprocessor = ColumnTransformer(
    transformers=[('cat', OneHotEncoder(handle_unknown='ignore'), multinominal_cols)],
    remainder="passthrough"
)

rf_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", RandomForestClassifier(random_state = 42))
    ]
)

# Logistic Regression Pipeline
preprocessor = ColumnTransformer(
    transformers=[('cat', OneHotEncoder(handle_unknown='ignore'), multinominal_cols)],
    remainder="passthrough"
)

lr_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", LogisticRegression(random_state = 42))
    ]
)

In [ ]:
df.drop(binary_cols, inplace=True, axis=1)
df.head()

,SeniorCitizen,tenure,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaymentMethod,MonthlyCharges,TotalCharges,gender_encoded,Partner_encoded,Dependents_encoded,PhoneService_encoded,PaperlessBilling_encoded,Churn_encoded
customerID,,,,,,,,,,,,,,,,,,,,
CUST0000,0,23,No phone service,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Bank transfer,49.85,1146.55,0,0,0,0,0,0
CUST0001,0,43,No phone service,DSL,Yes,No,Yes,No,Yes,No,Month-to-month,Mailed check,100.70,4330.10,1,1,1,0,1,1
CUST0002,1,51,No,DSL,No,Yes,Yes,Yes,No,No,One year,Electronic check,97.33,4963.83,0,0,1,1,1,1
CUST0003,1,72,Yes,DSL,Yes,No,Yes,No,No,No,Month-to-month,Credit card,101.38,7299.36,0,0,1,1,1,0
CUST0004,1,25,Yes,DSL,No,No,No,Yes,No,Yes,Month-to-month,Electronic check,52.22,1305.50,0,0,1,1,1,1

In [69]:
def best_model(X, y, pipeline):
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=42)

    
    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)

    return accuracy

In [80]:
X = df.drop('Churn_encoded', axis=1)
y = df['Churn_encoded']

print(f"{best_model(X, y, rf_pipeline)}, {best_model(X, y, lr_pipeline)}")

0.5076530612244898, 0.47874149659863946

/home/anees/Documents/Projects/customer-churn-prediction/.venv/lib64/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [14]:
model_coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
})
model_coefficients

                     Feature  Coefficient
0              SeniorCitizen    -0.010230
1                     tenure    -0.001656
2             MonthlyCharges    -0.000915
3               TotalCharges     0.000033
4             gender_encoded    -0.006835
5            Partner_encoded     0.017495
6         Dependents_encoded    -0.004004
7       PhoneService_encoded    -0.031137
8      MultipleLines_encoded    -0.045315
9    InternetService_encoded     0.012121
10    OnlineSecurity_encoded     0.009073
11      OnlineBackup_encoded     0.017046
12  DeviceProtection_encoded    -0.025622
13       TechSupport_encoded    -0.037972
14       StreamingTV_encoded    -0.001998
15   StreamingMovies_encoded    -0.009362
16          Contract_encoded     0.071385
17  PaperlessBilling_encoded     0.004959
18     PaymentMethod_encoded     0.013619