In [20]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("customer_churn_data.csv", index_col="customerID")
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
customerID,,,,,,,,,,,,,,,,,,,,
CUST0000,Male,0,No,Yes,23,No,No phone service,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer,49.85,1146.55,No
CUST0001,Female,0,Yes,No,43,No,No phone service,DSL,Yes,No,Yes,No,Yes,No,Month-to-month,No,Mailed check,100.70,4330.10,Yes
CUST0002,Male,1,No,No,51,Yes,No,DSL,No,Yes,Yes,Yes,No,No,One year,No,Electronic check,97.33,4963.83,Yes
CUST0003,Male,1,No,No,72,Yes,Yes,DSL,Yes,No,Yes,No,No,No,Month-to-month,No,Credit card,101.38,7299.36,No
CUST0004,Male,1,No,No,25,Yes,Yes,DSL,No,No,No,Yes,No,Yes,Month-to-month,No,Electronic check,52.22,1305.50,Yes

In [3]:
# Checking for null variables or inconsistencies within the dataframe
df.info()

<class 'pandas.DataFrame'>
Index: 5880 entries, CUST0000 to CUST5879
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            5880 non-null   str
 1   SeniorCitizen     5880 non-null   int64
 2   Partner           5880 non-null   str
 3   Dependents        5880 non-null   str
 4   tenure            5880 non-null   int64
 5   PhoneService      5880 non-null   str
 6   MultipleLines     5880 non-null   str
 7   InternetService   5880 non-null   str
 8   OnlineSecurity    5880 non-null   str
 9   OnlineBackup      5880 non-null   str
 10  DeviceProtection  5880 non-null   str
 11  TechSupport       5880 non-null   str
 12  StreamingTV       5880 non-null   str
 13  StreamingMovies   5880 non-null   str
 14  Contract          5880 non-null   str
 15  PaperlessBilling  5880 non-null   str
 16  PaymentMethod     5880 non-null   str
 17  MonthlyCharges    5880 non-null   float64
 18  TotalCharges      5880 non-null   float64
 19  Churn             5880 non-null   str
dtypes: float64(2), int64(2), str(16)
memory usage: 964.7+ KB

In [4]:
for col in df.columns:
    print(f"{df[col].name}: {df[col].nunique()}")

gender: 2
SeniorCitizen: 2
Partner: 2
Dependents: 2
tenure: 72
PhoneService: 2
MultipleLines: 3
InternetService: 3
OnlineSecurity: 3
OnlineBackup: 3
DeviceProtection: 3
TechSupport: 3
StreamingTV: 3
StreamingMovies: 3
Contract: 3
PaperlessBilling: 2
PaymentMethod: 4
MonthlyCharges: 4439
TotalCharges: 5794
Churn: 2

In [5]:
cols_to_adjust = df.iloc[:, 8:14].columns

In [7]:
df[cols_to_adjust] = df[cols_to_adjust].replace('No internet service', 'No')
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
customerID,,,,,,,,,,,,,,,,,,,,
CUST0000,Male,0,No,Yes,23,No,No phone service,No,No,No,No,No,No,No,Month-to-month,Yes,Bank transfer,49.85,1146.55,No
CUST0001,Female,0,Yes,No,43,No,No phone service,DSL,Yes,No,Yes,No,Yes,No,Month-to-month,No,Mailed check,100.70,4330.10,Yes
CUST0002,Male,1,No,No,51,Yes,No,DSL,No,Yes,Yes,Yes,No,No,One year,No,Electronic check,97.33,4963.83,Yes
CUST0003,Male,1,No,No,72,Yes,Yes,DSL,Yes,No,Yes,No,No,No,Month-to-month,No,Credit card,101.38,7299.36,No
CUST0004,Male,1,No,No,25,Yes,Yes,DSL,No,No,No,Yes,No,Yes,Month-to-month,No,Electronic check,52.22,1305.50,Yes

In [8]:
multinominal_cols = [col for col in df.select_dtypes(include=["object","str"]).columns if df[col].nunique() > 2 ] 
binary_cols = [col for col in df.select_dtypes(include=["object","str"]).columns if df[col].nunique() == 2 ]

In [9]:
def numericize_col(df, object_cols):
    for col in object_cols:
        df[f'{col}_encoded'] = pd.factorize(df[col])[0]
    return df

df = numericize_col(df, binary_cols)

In [29]:
cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
df[cols].describe()

            tenure  MonthlyCharges  TotalCharges
count  5880.000000     5880.000000   5880.000000
mean     36.549150       70.157779   2566.813165
std      20.909674       28.804615   1910.017743
min       1.000000       20.000000     20.030000
25%      18.000000       45.717500   1020.217500
50%      37.000000       70.155000   2136.445000
75%      55.000000       95.457500   3767.665000
max      72.000000      119.990000   8589.600000

In [ ]:
# Random Forest Classifier Pipeline
preprocessor = ColumnTransformer(
    transformers=[('cat', OneHotEncoder(handle_unknown='ignore'), multinominal_cols)],
    remainder="passthrough"
)

rf_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", RandomForestClassifier(random_state = 42))
    ]
)

# Logistic Regression Pipeline
preprocessor = ColumnTransformer(
    transformers=[('cat', OneHotEncoder(handle_unknown='ignore'), multinominal_cols)],
    remainder="passthrough"
)

lr_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(random_state = 42))
    ]
)

In [11]:
df.drop(binary_cols, inplace=True, axis=1)
df.head()

,SeniorCitizen,tenure,MultipleLines,InternetService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,gender_encoded,Partner_encoded,Dependents_encoded,PhoneService_encoded,OnlineSecurity_encoded,OnlineBackup_encoded,DeviceProtection_encoded,TechSupport_encoded,StreamingTV_encoded,StreamingMovies_encoded,PaperlessBilling_encoded,Churn_encoded
customerID,,,,,,,,,,,,,,,,,,,,
CUST0000,0,23,No phone service,No,Month-to-month,Bank transfer,49.85,1146.55,0,0,0,0,0,0,0,0,0,0,0,0
CUST0001,0,43,No phone service,DSL,Month-to-month,Mailed check,100.70,4330.10,1,1,1,0,1,0,1,0,1,0,1,1
CUST0002,1,51,No,DSL,One year,Electronic check,97.33,4963.83,0,0,1,1,0,1,1,1,0,0,1,1
CUST0003,1,72,Yes,DSL,Month-to-month,Credit card,101.38,7299.36,0,0,1,1,1,0,1,0,0,0,1,0
CUST0004,1,25,Yes,DSL,Month-to-month,Electronic check,52.22,1305.50,0,0,1,1,0,0,0,1,0,1,1,1

In [ ]:
def best_model(X, y, pipeline):
    X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=42)

    
    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)

    return accuracy

In [42]:
X = df.drop('Churn_encoded', axis=1)
y = df['Churn_encoded']

print(f"{best_model(X, y, rf_pipeline)}")

0.4957482993197279

In [81]:
feature_names = rf_pipeline.named_steps['preprocessor'].get_feature_names_out()
feature_importance = rf_pipeline.named_steps['model'].feature_importances_

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": feature_importance
}).sort_values(by="Importance", ascending=False)
importance_df

                                Feature  Importance
16              remainder__TotalCharges    0.171731
15            remainder__MonthlyCharges    0.171095
14                    remainder__tenure    0.148372
13             remainder__SeniorCitizen    0.031557
17            remainder__gender_encoded    0.031193
27  remainder__PaperlessBilling_encoded    0.030001
19        remainder__Dependents_encoded    0.029188
18           remainder__Partner_encoded    0.028729
25       remainder__StreamingTV_encoded    0.022619
26   remainder__StreamingMovies_encoded    0.022603
22      remainder__OnlineBackup_encoded    0.021751
21    remainder__OnlineSecurity_encoded    0.021003
10       cat__PaymentMethod_Credit card    0.020573
24       remainder__TechSupport_encoded    0.020509
23  remainder__DeviceProtection_encoded    0.020435
9      cat__PaymentMethod_Bank transfer    0.019507
11  cat__PaymentMethod_Electronic check    0.019501
12      cat__PaymentMethod_Mailed check    0.019484
8                cat__Contract_Two year    0.018687
7                cat__Contract_One year    0.018673
6          cat__Contract_Month-to-month    0.018358
3              cat__InternetService_DSL    0.016467
4      cat__InternetService_Fiber optic    0.015561
2                cat__MultipleLines_Yes    0.015135
0                 cat__MultipleLines_No    0.014211
20      remainder__PhoneService_encoded    0.012065
1   cat__MultipleLines_No phone service    0.011401
5               cat__InternetService_No    0.009590

In [72]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['MultipleLines', 'InternetService',
                                  'Contract', 'PaymentMethod'])])

In [ ]:
model_coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
})
model_coefficients